apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: search-service
data:
  ADMIN_USER: admin
  ADMIN_PASSWORD: password
  ADMIN_JWT_KEY: your-secret-key
  TOKEN_TTL: 2m
  API_ADDRESS: :8080
  WORDS_ADDRESS: words:8081
  UPDATE_ADDRESS: update:8082
  SEARCH_ADDRESS: search:8083
  SEARCH_CONCURRENCY: "10"
  SEARCH_RATE: "100"
