apiVersion: v1
kind: ConfigMap
metadata:
  name: update-config
  namespace: search-service
data:
  UPDATE_ADDRESS: :8082
  WORDS_ADDRESS: words:8081
  XKCD_CONCURRENCY: "10"
  XKCD_URL: https://xkcd.com
  DB_ADDRESS: postgres://postgres:password@postgres:5432/postgres
  BROKER_ADDRESS: nats://nats:4222
  BROKER_SUBJECT: xkcd.db.updated
