apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-deployment
  namespace: search-service
  labels:
    app: update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update
  template:
    metadata:
      labels:
        app: update
    spec:
      containers:
      - name: update
        image: update:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: update-config
