apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-deployment
  namespace: search-service
  labels:
    app: words
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - name: words
        image: words:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: words-config
