name: XKCD Search service CI

on:
  push:
    branches: ["main", "dev"]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: golangci-lint
        run: |
          curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.7.2
          go install github.com/yoheimuta/protolint/cmd/protolint@latest
          make lint

  security:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          make security

  build:
    needs: [lint, security]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Build all images
        run: make build-images

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run Integration Tests
        run: |
          make integration-tests

      - name: Coveralls GitHub Action
        run: |
          make cover
      - uses: coverallsapp/github-action@v2.3.6
        with:
          file: cover.out
